"""Gemini cloud text-to-speech → 24 kHz mono PCM.

A near-human alternative to the local Kokoro engine, selected via
``Settings.tts_engine == "gemini"``.  Uses the SAME ``google-genai`` SDK and
``GEMINI_API_KEY`` that the brain already uses, so it introduces **no new trust
boundary**: FRIDAY's response text is generated by Gemini, and synthesising that
same text crosses the exact boundary that already exists.

Trade-off vs Kokoro (MEASURED 2026-06-23 on this machine)
---------------------------------------------------------
- Quality:    near-human (vs Kokoro's small-model timbre).
- First-audio: ~3-5 s fixed floor per request (network + model), roughly
  independent of length.  Because the floor is per-request, the caller should
  synthesise the WHOLE reply in one call (whole-utterance), NOT chunk it.
- RTF ~0.85-1.0x; non-streaming (the full clip returns at once).

API shape (google-genai 2.9.0, verified live)
----------------------------------------------
    resp = client.models.generate_content(
        model="gemini-2.5-flash-preview-tts",
        contents=text,
        config=types.GenerateContentConfig(
            response_modalities=["AUDIO"],
            speech_config=types.SpeechConfig(
                voice_config=types.VoiceConfig(
                    prebuilt_voice_config=types.PrebuiltVoiceConfig(
                        voice_name="Kore"))),
        ),
    )
    pcm = resp.candidates[0].content.parts[0].inline_data.data
    # mime_type = "audio/L16;codec=pcm;rate=24000"  -> 16-bit LE mono @ 24 kHz

The blocking SDK call is run in a thread so the event-loop is never blocked.
The transcript is NOT logged (only its length), matching the no-secrets-to-disk
posture.
"""

from __future__ import annotations

import asyncio
import logging
import os
from collections.abc import AsyncIterator

import numpy as np

logger = logging.getLogger(__name__)

# Gemini native sample rate for TTS output.
_NATIVE_RATE = 24_000
_DEFAULT_MODEL = "gemini-2.5-flash-preview-tts"
_DEFAULT_VOICE = "Kore"

# Module-level API key, set by init()/preload() from Settings.  Falls back to
# the GEMINI_API_KEY / GOOGLE_API_KEY environment variables if unset.
_api_key: str | None = None
_client: "object | None" = None  # google.genai.Client at runtime
_client_lock = asyncio.Lock()


def init(api_key: str | None) -> None:
    """Provide the API key (from Settings) before the first synth call.

    The app loads the key from .env via Settings, which does not export it to
    os.environ, so we pass it explicitly here rather than relying on the SDK's
    env auto-detection.
    """
    global _api_key
    if api_key:
        _api_key = api_key


def _build_client() -> "object":
    try:
        from google import genai  # type: ignore[import]
    except ImportError as exc:  # pragma: no cover - genai is a core dep
        raise RuntimeError(
            "google-genai is not installed; required for the Gemini TTS engine."
        ) from exc

    key = _api_key or os.environ.get("GEMINI_API_KEY") or os.environ.get("GOOGLE_API_KEY")
    if not key:
        raise RuntimeError(
            "No Gemini API key available for TTS. Call tts_gemini.init(api_key) "
            "at startup or set GEMINI_API_KEY."
        )
    return genai.Client(api_key=key)


async def _get_client() -> "object":
    global _client
    if _client is not None:
        return _client
    async with _client_lock:
        if _client is None:
            loop = asyncio.get_running_loop()
            _client = await loop.run_in_executor(None, _build_client)
    return _client


async def preload(api_key: str | None = None) -> None:
    """Build the client up front so the first turn doesn't pay client setup.

    Idempotent.  Unlike Kokoro there is no local model to download, so this is
    cheap; it just constructs the SDK client (and records the API key).
    """
    if api_key:
        init(api_key)
    await _get_client()
    logger.info("Gemini TTS client ready (engine=gemini).")


def _extract_pcm(resp: "object") -> bytes:
    """Pull raw PCM bytes out of a generate_content audio response."""
    try:
        part = resp.candidates[0].content.parts[0]  # type: ignore[attr-defined]
        data = part.inline_data.data
    except (AttributeError, IndexError, TypeError) as exc:
        raise RuntimeError(f"Gemini TTS response had no audio payload: {exc}") from exc
    if not data:
        raise RuntimeError("Gemini TTS returned empty audio.")
    return data


def _resample_i16(pcm: bytes, src_rate: int, dst_rate: int) -> bytes:
    if dst_rate == src_rate:
        return pcm
    arr = np.frombuffer(pcm, dtype=np.int16).astype(np.float32)
    n_out = int(len(arr) * dst_rate / src_rate)
    if n_out <= 0:
        return b""
    out = np.interp(
        np.linspace(0, len(arr) - 1, n_out),
        np.arange(len(arr)),
        arr,
    ).astype(np.int16)
    return out.tobytes()


async def synth(
    text: str,
    *,
    voice: str = _DEFAULT_VOICE,
    sample_rate: int = _NATIVE_RATE,
    model: str = _DEFAULT_MODEL,
) -> AsyncIterator[bytes]:
    """Synthesise *text* via Gemini and yield raw 16-bit LE PCM at *sample_rate*.

    Non-streaming: the full clip is fetched in one blocking SDK call (run in a
    thread) and yielded as a single chunk.  Mirrors ``tts_kokoro.synth`` so it
    is a drop-in for the stream.py TTS worker.
    """
    client = await _get_client()
    from google.genai import types  # type: ignore[import]

    def _call() -> bytes:
        resp = client.models.generate_content(  # type: ignore[attr-defined]
            model=model,
            contents=text,
            config=types.GenerateContentConfig(
                response_modalities=["AUDIO"],
                speech_config=types.SpeechConfig(
                    voice_config=types.VoiceConfig(
                        prebuilt_voice_config=types.PrebuiltVoiceConfig(
                            voice_name=voice
                        )
                    )
                ),
            ),
        )
        return _extract_pcm(resp)

    logger.debug("Gemini TTS synthesising %d chars (voice=%s)", len(text), voice)
    pcm = await asyncio.to_thread(_call)
    yield _resample_i16(pcm, _NATIVE_RATE, sample_rate)


async def synth_to_numpy(
    text: str,
    *,
    voice: str = _DEFAULT_VOICE,
    sample_rate: int = _NATIVE_RATE,
    model: str = _DEFAULT_MODEL,
) -> list[np.ndarray]:
    """Convenience wrapper returning a list with one float32 array (for tests)."""
    chunks: list[np.ndarray] = []
    async for pcm in synth(text, voice=voice, sample_rate=sample_rate, model=model):
        if pcm:
            chunks.append(np.frombuffer(pcm, dtype=np.int16).astype(np.float32) / 32768.0)
    return chunks
